# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the version of Python and OS
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      # Command to ensure we have the latest pip
      - pip install --upgrade pip

# Build documentation in the docs/source directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false
  builder: html

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Important: Install order matters for proper dependency resolution
python:
  install:
    # 1. Install documentation-specific dependencies first
    - requirements: docs/requirements.txt
    # 2. Then, install the package itself with all its dependencies
    - method: pip
      path: .
